import chalk from "chalk";
import os from "os";

console.clear();

console.log(chalk.cyan(`====================================`));
console.log(chalk.green(`\tSYSTEM INFO CLI TOOL`));
console.log(chalk.cyan(`====================================`));
let platform = os.platform();
console.log(chalk.hex('#ff57')(`\n📌 Platform :`),platform);
let type = os.type();
console.log(chalk.hex(`#ff57`)(`📌 OS type:`),type);
let release = os.release();
console.log(chalk.hex(`#ff57`)(`📌 Release:`),release);
let arch = os.arch();
console.log(chalk.hex(`#ff57`)(`📌 Architecture:`),arch);
let hname = os.hostname();
console.log(chalk.hex(`#ff57`)(`📌 Hostname:`),hname);
console.log(chalk.hex('#a90351ff')(`\n🧠 CPU INFO`));
let cpus = os.cpus().length.toString();
console.log(chalk.magenta(`Cores:`),cpus);
let model = os.cpus();
console.log(chalk.magenta(`Model:`),model[0].model);
console.log(chalk.hex('#0452f9f0')(`\n💾 Memory Info`));
let tmem = (os.totalmem()/1024/1024/1024).toFixed(2);
console.log(chalk.blue(`Total Memory:`), tmem, "GB");
let fmem = (os.freemem()/1024/1024/1024).toFixed(2);
console.log(chalk.blue(`Free Memory:`), fmem, "GB");
console.log(chalk.hex('#04fb63ff')(`\n🌐 Network Interfaces`));
let iface = os.networkInterfaces();
console.log(chalk.green(`Interface (Wi-Fi):`), iface.lo[1].address);
console.log(chalk.green(`Interface (Loopback Pseudo-interface 1):`), iface.lo[0].address);
console.log(chalk.green(`Interface (vEthernet (WSL (Hyper-V firewall))):`), iface.eth0[0].address);
console.log(chalk.hex('#f700b1ff')(`\n⌛ Uptime`));
let uptime = (os.uptime()/3600).toFixed(2);
console.log(chalk.hex('#880505ff')(`Uptime (Seconds):`),uptime,'hrs');
let homeD = os.homedir();
console.log(chalk.hex('#06a1f5c6')("\n🏡 Home Directory:"),homeD);
let tempD = os.tmpdir();
console.log(chalk.hex('#06a1f5c6')("📂 Temp Directory:"),tempD);
console.log(chalk.hex('#02952ec2')('✔️ System Info Retrived Successfully!'));
